'use strict';
const labels={about:'사서원 사업 소개',partners:'다른 기관 사업',apply:'대상별 사업 신청',resources:'자료·정보',self:'당사자 자유게시판',parents:'부모·보호자 자유게시판',suggest:'사서원에 건의',guide:'이용 안내'};
const escapeHTML=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const ext=(url,text)=>`<a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${text} (새 창)</a>`;
const sources={busan:'https://busan.pass.or.kr/',youth:'https://www.busan1365.kr/bbs/board.php?bo_table=news&wr_id=3275',seoul:'https://sbifc.org/',ulsan:'https://www.hmmcoop.co.kr/56'};
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4000);}
function page(id){
 if(id==='about')return `<span class="eyebrow">BUSAN SOCIAL SERVICE AGENCY</span><h2>함께 배우고, 일상을 넓혀갑니다.</h2><p class="lead">부산 경계선지능 청년의 사회 참여와 자립을 응원합니다.</p><div class="card"><span class="tag">2026년 사업 안내</span><h3>청년 자립교육 및 일경험</h3><p>부산에 거주하는 경계선지능 청년을 대상으로 사회성과 직업 기초역량을 기르는 교육, 면접, 현장 일경험 등을 지원합니다.</p><p><b>대상</b> · 부산시 거주 18~39세 경계선지능 청년<br><b>공고상 규모</b> · 60명</p><p class="small">접수 기간, 구체적인 선정 기준과 제출 서류는 최신 공식 공고에서 확인해 주세요. 이 화면은 현재 모집 중임을 의미하지 않습니다.</p>${ext(sources.youth,'모집 안내 출처 확인')} · ${ext(sources.busan,'부산사회서비스원')}</div><h3>내일을 향한 세 가지 걸음</h3><div class="steps"><div><b>01</b>함께 배우기<br>사회성과 직업 기초역량 교육</div><div><b>02</b>도전 준비하기<br>면접 등 일경험 준비</div><div><b>03</b>현장에서 경험하기<br>일상 밖으로 넓어지는 배움</div></div><button class="primary" data-open="apply">대상별 신청 안내 보기</button><div class="notice">공식 운영기관의 사업 범위와 세부 내용이 확정되면 이 페이지에 추가할 수 있습니다.</div>`;
 if(id==='partners')return `<span class="eyebrow">CONNECTED SUPPORT</span><h2>다른 지역의 배움도 함께 잇습니다.</h2><p class="lead">경계선지능인 지원기관의 공식 정보를 만나보세요.</p><div class="tabs" role="group" aria-label="지역 선택"><button class="selected" data-region="all">전체</button><button data-region="seoul">서울</button><button data-region="ulsan">울산</button></div><div class="cards" id="partner-list"><article class="card" data-place="seoul"><span class="tag">서울 · 참고기관</span><h3>서울시 경계선지능인 평생교육 지원센터</h3><p>경계선지능인 지원과 평생교육 관련 사업을 확인할 수 있는 참고 기관입니다.</p>${ext(sources.seoul,'센터 공식 홈페이지')}</article><article class="card" data-place="ulsan"><span class="tag">울산 · 참고기관</span><h3>함께만드는마을 사회적협동조합</h3><p>경계선지능인지원센터 안내를 제공하는 기관입니다. 구체적인 프로그램은 기관에 확인해 주세요.</p>${ext(sources.ulsan,'경계선지능인지원센터 안내')}</article></div><div class="notice">다른 지역 기관은 부산시 사업과 신청 기준이 다를 수 있습니다. 거주지·연령·접수 여부를 각 기관에서 확인해 주세요.</div><p class="small">부산 지역 유관기관 사업 목록은 운영기관이 확인한 공고를 기준으로 추가할 예정입니다.</p>`;
 if(id==='apply')return `<span class="eyebrow">FIND YOUR NEXT STEP</span><h2>나에게 맞는 지원부터 찾아보세요.</h2><p class="lead">신청하는 분의 상황을 선택하면 안내가 바뀝니다.</p><div class="tabs" role="group" aria-label="신청 대상"><button class="selected" data-audience="youth">청년 당사자</button><button data-audience="children">아동·청소년</button><button data-audience="parents">부모·보호자</button><button data-audience="workers">기관·종사자</button></div><div id="audience-detail"></div><h3>신청은 이렇게 진행해요</h3><div class="steps"><div><b>01</b>대상과 모집 기간 확인</div><div><b>02</b>공식 접수 페이지에서 신청</div><div><b>03</b>운영기관의 안내 확인</div></div><details><summary>내가 신청 대상인지 잘 모르겠어요.</summary><p>공식 공고의 대상과 선정 기준을 먼저 확인해 주세요. 판단이 어려우면 운영기관에 문의해 주세요. 이 홈페이지는 검사나 지원 대상 판정을 하지 않습니다.</p></details><details><summary>여기에 개인정보를 입력해야 하나요?</summary><p>이 제작 시안은 개인정보나 검사자료를 수집하지 않습니다. 실제 신청은 운영기관의 공식 접수 페이지에서 진행해 주세요.</p></details>`;
 if(id==='resources')return `<span class="eyebrow">LEARN & UNDERSTAND</span><h2>이해가 깊어지면, 함께할 길이 보입니다.</h2><p class="lead">쉬운 이용 안내와 공식 기관 정보를 모았습니다.</p><div class="cards"><div class="card"><span class="tag">쉬운 안내</span><h3>부산 한걸음의 함께 이용 안내</h3><p>사업을 찾아보고, 서로를 존중하며 이야기를 나누는 방법을 정리했습니다.</p><button class="link-button" data-download="guide">이용 안내 다운로드 (.txt)</button></div><div class="card"><span class="tag">신청 준비</span><h3>공고 확인 체크리스트</h3><p>대상, 기간, 서류, 접수 방법을 한 번씩 확인해 보세요.</p><button class="link-button" data-download="checklist">체크리스트 다운로드 (.txt)</button></div></div><h3>공식 정보를 찾는 곳</h3><div class="row">${ext(sources.busan,'부산광역시사회서비스원')}<span>사업·신청 공고</span></div><div class="row">${ext(sources.seoul,'서울시 경계선지능인 평생교육 지원센터')}<span>지원·교육 정보</span></div><div class="row">${ext(sources.ulsan,'함께만드는마을 경계선지능인지원센터')}<span>기관 안내</span></div><h3>자주 묻는 질문</h3><details><summary>모든 사람에게 같은 도움이 필요한가요?</summary><p>사람마다 배움과 일상에서 필요한 도움은 다릅니다. 자신의 경험과 필요를 운영기관과 이야기하며 적합한 지원을 확인해 주세요.</p></details><details><summary>자료를 홈페이지에 올리고 싶어요.</summary><p>자료의 출처와 공개·배포 가능 여부를 확인한 뒤 사서원에 건의 메뉴로 제안을 준비할 수 있습니다. 현재는 제안 문안을 작성하는 시안입니다.</p></details><p class="small">전문 자료·연구 보고서·정책 자료는 운영기관의 검토를 거쳐 추가할 수 있습니다.</p>`;
 if(['self','parents','suggest'].includes(id))return boardHTML(id);
 return '';
}
function handleSectionClick(event,win,id){
 const audience=event.target.closest('[data-audience]')?.dataset.audience;if(audience)setAudience(win,audience);
 const region=event.target.closest('[data-region]')?.dataset.region;if(region){win.querySelectorAll('[data-region]').forEach(b=>{b.classList.toggle('selected',b.dataset.region===region);b.setAttribute('aria-pressed',String(b.dataset.region===region));});win.querySelectorAll('[data-place]').forEach(c=>c.hidden=region!=='all'&&region!==c.dataset.place);}
 if(event.target.closest('[data-compose]'))compose(win,id);
 if(event.target.closest('[data-back-board]')){win.innerHTML=boardHTML(id);renderPosts(win,id);}
 const post=event.target.closest('[data-post]')?.dataset.post;if(post)readPost(win,id,post);
 if(event.target.closest('[data-preview]'))previewDraft(win,id);
 if(event.target.closest('[data-save-draft]'))saveDraft(win,id);
 if(event.target.closest('[data-export-draft]'))exportDraft(win,id);
 const remove=event.target.closest('[data-remove-post]')?.dataset.removePost;if(remove){if(setDrafts(id,getDrafts(id).filter(p=>p.id!==remove))){win.innerHTML=boardHTML(id);renderPosts(win,id);toast('이 기기에 저장한 초안을 삭제했습니다.');}}
}
const audiences={youth:{title:'청년 당사자',description:'청년 자립교육 및 일경험',body:'2026년 안내 공고 기준 부산시 거주 18~39세 경계선지능 청년이 대상입니다. 최신 모집 기간과 선정 기준은 공식 공고를 확인해 주세요.'},children:{title:'아동·청소년',description:'아동·청소년 지원 안내',body:'아동·청소년 대상 사업의 모집 공고와 신청 기준은 아직 이 시안에 등록되지 않았습니다. 운영기관의 공식 안내를 확인해 주세요.'},parents:{title:'부모·보호자',description:'부모·보호자 참여 안내',body:'보호자 교육·모임 등 대상별 모집 공고는 운영기관 확인 후 등록할 수 있습니다. 청년의 사업 신청을 도울 때는 해당 공고의 대리 신청 기준을 확인해 주세요.'},workers:{title:'기관·종사자',description:'기관·종사자 참여 안내',body:'협력기관이나 종사자 대상 사업의 모집 공고는 운영기관 확인 후 등록할 수 있습니다. 협력 제안은 사서원에 건의 메뉴에서 문안을 준비해 주세요.'}};
function setAudience(win,type){win.querySelectorAll('[data-audience]').forEach(b=>{b.classList.toggle('selected',b.dataset.audience===type);b.setAttribute('aria-pressed',String(b.dataset.audience===type));});const a=audiences[type];const url=window.SITE_CONFIG?.applications[type];let valid=false;try{valid=!!url&&new URL(url).protocol==='https:';}catch{}
 win.querySelector('#audience-detail').innerHTML=`<div class="card"><span class="tag">${a.title}</span><h3>${a.description}</h3><p>${a.body}</p>${valid?`<a class="primary" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">공식 신청 페이지 열기 (새 창)</a>`:`<div class="notice">이 시안에서는 직접 신청을 접수하지 않습니다. 공식 홈페이지에서 현재 공고를 확인해 주세요.</div><a class="primary" href="${sources.busan}" target="_blank" rel="noopener noreferrer">공식 신청 공고 확인 (새 창)</a>`}${type==='youth'?`<p class="small">${ext(sources.youth,'2026년 청년 사업 안내 출처')}</p>`:''}</div>`;
}
function getDrafts(id){try{const data=JSON.parse(localStorage.getItem('ieum-drafts-'+id)||'[]');return Array.isArray(data)?data.filter(p=>p&&typeof p.id==='string'&&typeof p.title==='string'&&typeof p.body==='string'):[];}catch{return [];}}
function setDrafts(id,posts){try{localStorage.setItem('ieum-drafts-'+id,JSON.stringify(posts));return true;}catch{toast('기기에 저장할 수 없습니다. 문안을 다운로드해 주세요.');return false;}}
function boardHTML(id){const suggest=id==='suggest';return `<span class="eyebrow">${suggest?'YOUR IDEAS, OUR TOMORROW':'OUR STORIES, OUR COMMUNITY'}</span><h2>${suggest?'더 나은 한걸음을 위한 생각':id==='self'?'나의 이야기가, 누군가의 응원이 됩니다.':'함께 돌보고, 함께 힘을 얻어요.'}</h2><p class="lead">${suggest?'사업과 홈페이지에 대한 의견을 사서원에 제안하는 공간입니다.':id==='self'?'일상의 발견과 도전, 나누고 싶은 이야기를 적어 보세요.':'부모와 보호자가 경험을 나누는 소통 공간입니다.'}</p><div class="notice">제작 시안 · 작성한 글은 운영기관에 전송되지 않습니다. ‘이 기기에 초안 저장’을 선택한 글만 이 브라우저에 보관됩니다.</div><div class="toolbar"><input type="search" data-board-search aria-label="초안 검색" placeholder="이 기기의 초안 검색"><button class="primary" data-compose>${suggest?'건의문 작성':'글 작성'}</button></div><div data-post-list></div><p class="small">개인정보·진단자료는 작성하지 마세요. 초안은 다른 이용자에게 보이지 않습니다.</p>`;}
function renderPosts(win,id){const draw=()=>{const q=win.querySelector('[data-board-search]')?.value.trim().toLowerCase()||'';const drafts=getDrafts(id).filter(p=>(p.title+' '+p.body).toLowerCase().includes(q));win.querySelector('[data-post-list]').innerHTML=drafts.length?drafts.map(p=>`<button class="board-entry" data-post="${escapeHTML(p.id)}"><strong>${escapeHTML(p.title)}</strong><small>내 기기의 초안 · ${escapeHTML(p.date||'')}</small></button>`).join(''):`<div class="empty">${q?'검색 결과가 없습니다.':'아직 저장한 초안이 없습니다.'}<br><span class="small">문안을 작성하고 미리 볼 수 있어요.</span></div>`;};draw();win.querySelector('[data-board-search]')?.addEventListener('input',draw);}
function compose(win,id){const suggest=id==='suggest';win.innerHTML=`<button class="text-button" data-back-board>목록으로</button><h2>${suggest?'사서원에 건의문 작성':'나의 이야기 작성'}</h2><p class="small">현재는 문안 작성 기능입니다. 실제 전송·게시되지 않습니다.</p><form id="draft-form-${id}">${suggest?`<label for="draft-category-${id}">건의 분야</label><select id="draft-category-${id}" name="category"><option>사업 제안</option><option>홈페이지 이용 개선</option><option>자료·정보 제안</option><option>기타</option></select>`:''}<label for="draft-title-${id}">제목</label><input id="draft-title-${id}" name="title" required maxlength="100" placeholder="제목을 적어 주세요"><label for="draft-body-${id}">내용</label><textarea id="draft-body-${id}" name="body" required maxlength="10000" placeholder="개인정보 없이, 나누고 싶은 이야기를 적어 주세요"></textarea><div class="draft-actions"><button type="button" class="primary" data-preview>문안 미리보기</button><button type="button" class="link-button" data-save-draft>이 기기에 초안 저장</button><button type="button" class="link-button" data-export-draft>문안 다운로드</button></div></form><div id="draft-preview-${id}" hidden></div>`;win.querySelector('form').addEventListener('submit',event=>event.preventDefault());win.querySelector('[name=title]').focus({preventScroll:true});}
function draftData(win){const form=win.querySelector('form');if(!form||!form.reportValidity())return null;const f=new FormData(form);const title=f.get('title').trim(),body=f.get('body').trim();if(!title||!body){toast('제목과 내용을 적어 주세요.');return null;}return {id:String(Date.now())+'-'+Math.random().toString(36).slice(2,7),title,body,category:f.get('category')||'',date:new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})};}
function previewDraft(win){const d=draftData(win);if(!d)return;const target=win.querySelector('[id^=draft-preview-]');target.hidden=false;target.innerHTML=`<div class="card" style="margin-top:24px"><span class="tag">미리보기 · 전송되지 않음</span><h3>${escapeHTML(d.title)}</h3><p class="reading">${escapeHTML(d.body)}</p></div>`;target.scrollIntoView({block:'nearest',behavior:'smooth'});}
function saveDraft(win,id){const d=draftData(win);if(!d)return;if(!setDrafts(id,[d,...getDrafts(id)]))return;win.innerHTML=boardHTML(id);renderPosts(win,id);toast('이 기기에 초안을 저장했습니다. 실제 게시·전송되지 않았습니다.');}
function exportDraft(win,id){const d=draftData(win);if(!d)return;download(`${labels[id]}-문안.txt`,`${labels[id]} — 작성 문안 (미전송)\n${d.category}\n${d.title}\n\n${d.body}\n\n작성일: ${d.date}`);}
function readPost(win,id,key){const p=getDrafts(id).find(p=>p.id===key);if(!p)return;win.innerHTML=`<button class="text-button" data-back-board>목록으로</button><p class="small">내 기기의 초안 · 실제 게시·전송되지 않음</p><h2>${escapeHTML(p.title)}</h2><p class="small">${escapeHTML(p.category||'')} · ${escapeHTML(p.date||'')}</p><p class="reading">${escapeHTML(p.body)}</p><button class="link-button" data-remove-post="${escapeHTML(p.id)}">이 초안 삭제</button>`;}
function download(name,text){const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const downloadTexts={
guide:'부산 한걸음의 함께 이용 안내\n\n1. 첫 화면 아래 항목 또는 상단 메뉴를 누르면 해당 구역으로 이동합니다.\n2. 대상별 신청 탭에서 내 상황에 맞는 안내를 확인하세요.\n3. 실제 신청은 공식 접수 페이지에서 진행합니다.\n4. 게시판은 글 미리보기, 다운로드, 선택적 기기 초안 저장 기능을 제공합니다. 실제 게시·전송되지 않습니다.\n5. 타인의 개인정보와 검사자료를 올리지 마세요.',
checklist:'사업 신청 공고 확인 체크리스트\n\n□ 공식 운영기관의 최신 공고인가요?\n□ 거주지와 연령 기준을 확인했나요?\n□ 신청 대상과 선정 기준을 확인했나요?\n□ 접수 기간과 제출 방법을 확인했나요?\n□ 필요한 서류를 공식 공고에서 확인했나요?\n□ 개인정보 동의와 문의처를 확인했나요?\n\n이 자료는 이용 보조 안내이며 공식 신청 서식이 아닙니다.'};
document.querySelectorAll('[data-content]').forEach(el=>{const id=el.dataset.content;el.innerHTML=page(id);if(id==='apply')setAudience(el,'youth');if(id==='suggest')renderPosts(el,id);});
const community=document.getElementById('community-body');community.innerHTML=boardHTML('self');renderPosts(community,'self');
document.addEventListener('click',event=>{
 const area=event.target.closest('.section-body');if(area){const id=area.dataset.boardId||area.dataset.content;handleSectionClick(event,area,id);}
 const choice=event.target.closest('[data-board]');if(choice){const id=choice.dataset.board;community.dataset.boardId=id;community.innerHTML=boardHTML(id);renderPosts(community,id);document.querySelectorAll('[data-board]').forEach(b=>{b.classList.toggle('selected',b.dataset.board===id);b.setAttribute('aria-pressed',String(b.dataset.board===id));});}
 const target=event.target.closest('[data-open]');if(target){const name=target.dataset.open;document.getElementById(['self','parents'].includes(name)?'community':name)?.scrollIntoView({behavior:reducedMotion?'instant':'smooth'});}
 const file=event.target.closest('[data-download]')?.dataset.download;if(file&&downloadTexts[file])download(file==='guide'?'부산-한걸음의-함께-이용안내.txt':'사업신청-체크리스트.txt',downloadTexts[file]);
 if(event.target.closest('[data-guide]'))download('부산-한걸음의-함께-이용안내.txt',downloadTexts.guide);
});
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.getElementById('font-toggle').addEventListener('click',event=>{const on=document.body.classList.toggle('big-font');event.currentTarget.setAttribute('aria-pressed',String(on));event.currentTarget.setAttribute('aria-label',on?'큰 글씨 끄기':'큰 글씨 켜기');});
document.getElementById('back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:reducedMotion?'instant':'smooth'}));
function updateNavigation(){document.getElementById('back-top').hidden=scrollY<600;const sections=Array.from(document.querySelectorAll('.content-section'));const active=sections.filter(el=>el.getBoundingClientRect().top<=220).pop();document.querySelectorAll('.header nav a,.section-nav a').forEach(a=>{const selected=!!active&&a.hash==='#'+active.id;a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
window.addEventListener('scroll',updateNavigation,{passive:true});updateNavigation();
